version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./es_data:/usr/share/elasticsearch/data:rw"
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.10.1
    volumes: 
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports: 
      - "5601:5601"
    depends_on: 
      - es
